[package]
name = "redis-color"
version = "0.1.0"
authors = ["David Palm <dvdplm@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
bitflags = "1.0"
libc = "0.2"
time = "*"

[build-dependencies]
cc = "1.0.7"
